// <auto-generated />
using System;
using InternetShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternetShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternetShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("InternetShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("InternetShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("StorageConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 52,
                            Category = "Фрукты",
                            CreatedAt = new DateTime(2026, 6, 13, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1363),
                            Description = "Свежие, сочные яблоки с кисло-сладким вкусом. Урожай 2024 года.",
                            ExpiryDate = new DateTime(2026, 7, 13, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1383),
                            ImageUrl = "/images/apples.jpg",
                            IsOrganic = true,
                            Manufacturer = "Local Farm",
                            Name = "Яблоки Гренни Смит",
                            Price = 150m,
                            Stock = 100,
                            StorageConditions = "Хранить в холодильнике при +2-4°C",
                            Unit = "кг"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 77,
                            Category = "Овощи",
                            CreatedAt = new DateTime(2026, 6, 13, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1396),
                            Description = "Молодой картофель, выращенный в экологически чистых условиях",
                            ExpiryDate = new DateTime(2026, 6, 27, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1397),
                            ImageUrl = "/images/potato.jpg",
                            IsOrganic = true,
                            Manufacturer = "Фермерское хозяйство",
                            Name = "Картофель молодой",
                            Price = 80m,
                            Stock = 200,
                            StorageConditions = "Темное сухое место при +5-10°C",
                            Unit = "кг"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 165,
                            Category = "Мясо",
                            CreatedAt = new DateTime(2026, 6, 13, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1399),
                            Description = "Свежее куриное филе без кости и кожи. Охлажденное.",
                            ExpiryDate = new DateTime(2026, 6, 18, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1400),
                            ImageUrl = "/images/chicken.jpg",
                            IsOrganic = false,
                            Manufacturer = "Птицефабрика №1",
                            Name = "Куриное филе",
                            Price = 350m,
                            Stock = 50,
                            StorageConditions = "Хранить при температуре от 0 до +4°C",
                            Unit = "кг"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 60,
                            Category = "Молочные продукты",
                            CreatedAt = new DateTime(2026, 6, 13, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1402),
                            Description = "Пастеризованное молоко высшего качества",
                            ExpiryDate = new DateTime(2026, 6, 20, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1403),
                            ImageUrl = "/images/milk.jpg",
                            IsOrganic = false,
                            Manufacturer = "Молочная ферма",
                            Name = "Молоко 3.2%",
                            Price = 89m,
                            Stock = 150,
                            StorageConditions = "Хранить при температуре от +2 до +6°C",
                            Unit = "л"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 210,
                            Category = "Хлебобулочные",
                            CreatedAt = new DateTime(2026, 6, 13, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1405),
                            Description = "Свежевыпеченный ржаной хлеб на закваске",
                            ExpiryDate = new DateTime(2026, 6, 16, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1406),
                            ImageUrl = "/images/bread.jpg",
                            IsOrganic = false,
                            Manufacturer = "Хлебозавод",
                            Name = "Хлеб ржаной",
                            Price = 55m,
                            Stock = 30,
                            StorageConditions = "Хранить при комнатной температуре",
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 6,
                            Calories = 208,
                            Category = "Рыба",
                            CreatedAt = new DateTime(2026, 6, 13, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1407),
                            Description = "Филе лосося слабой соли, вакуумная упаковка",
                            ExpiryDate = new DateTime(2026, 6, 27, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1408),
                            ImageUrl = "/images/salmon.jpg",
                            IsOrganic = true,
                            Manufacturer = "Рыбный промысел",
                            Name = "Лосось слабосоленый",
                            Price = 850m,
                            Stock = 25,
                            StorageConditions = "Хранить при температуре от -2 до +2°C",
                            Unit = "кг"
                        },
                        new
                        {
                            Id = 7,
                            Calories = 18,
                            Category = "Овощи",
                            CreatedAt = new DateTime(2026, 6, 13, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1410),
                            Description = "Сладкие помидоры черри на ветке",
                            ExpiryDate = new DateTime(2026, 6, 23, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1411),
                            ImageUrl = "/images/tomatoes.jpg",
                            IsOrganic = true,
                            Manufacturer = "Тепличный комплекс",
                            Name = "Помидоры черри",
                            Price = 220m,
                            Stock = 80,
                            StorageConditions = "Хранить в холодильнике",
                            Unit = "кг"
                        },
                        new
                        {
                            Id = 8,
                            Calories = 431,
                            Category = "Молочные продукты",
                            CreatedAt = new DateTime(2026, 6, 13, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1412),
                            Description = "Твердый итальянский сыр 24 месяца выдержки",
                            ExpiryDate = new DateTime(2026, 12, 13, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1413),
                            ImageUrl = "/images/cheese.jpg",
                            IsOrganic = false,
                            Manufacturer = "Italy Cheese",
                            Name = "Сыр Пармезан",
                            Price = 1200m,
                            Stock = 40,
                            StorageConditions = "Хранить в холодильнике при +4-8°C",
                            Unit = "кг"
                        },
                        new
                        {
                            Id = 9,
                            Calories = 304,
                            Category = "Бакалея",
                            CreatedAt = new DateTime(2026, 6, 13, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1419),
                            Description = "Натуральный цветочный мед без добавок",
                            ExpiryDate = new DateTime(2028, 6, 13, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1420),
                            ImageUrl = "/images/honey.jpg",
                            IsOrganic = true,
                            Manufacturer = "Пасека",
                            Name = "Мед цветочный",
                            Price = 450m,
                            Stock = 60,
                            StorageConditions = "Хранить при комнатной температуре",
                            Unit = "кг"
                        },
                        new
                        {
                            Id = 10,
                            Calories = 23,
                            Category = "Зелень",
                            CreatedAt = new DateTime(2026, 6, 13, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1423),
                            Description = "Молодой свежий шпинат в упаковке",
                            ExpiryDate = new DateTime(2026, 6, 18, 23, 28, 40, 604, DateTimeKind.Local).AddTicks(1424),
                            ImageUrl = "/images/spinach.jpg",
                            IsOrganic = true,
                            Manufacturer = "Green Farm",
                            Name = "Шпинат свежий",
                            Price = 120m,
                            Stock = 45,
                            StorageConditions = "Хранить в холодильнике при +2-4°C",
                            Unit = "100г"
                        });
                });

            modelBuilder.Entity("InternetShop.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InternetShop.Models.Order", b =>
                {
                    b.HasOne("InternetShop.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternetShop.Models.OrderItem", b =>
                {
                    b.HasOne("InternetShop.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternetShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InternetShop.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InternetShop.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternetShop.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InternetShop.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InternetShop.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("InternetShop.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
